<a href="https://colab.research.google.com/github/RUDRAMADHABA/DSC-30-Days-of-Web/blob/main/Rudramadhaba_mishra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Here are some important libraries

In [ ]:
import pandas as pd
import numpy as np


loading iris function

In [ ]:
From sklearn.datasets import load_iris
iris_dataset = load_iris()

iris object containing keys and values.

In [ ]:
print(“keys of iris_dataset: \n{}”.format(iris_dataset.key()))
keys of iris_dataset:
dist_keys(['data','target','target_names','DESCR','features_names','filename'])

Lets see what key DESCR contains

In [ ]:
print(iris_dataset['DESCR'][:193]+"\n....")
..iris_dataset:
iris plants dataset
..........
**dataset of characteristics:**
:Number of Instances:150(50 in each of three classes)
:Numbers of Attributes:4 numeric,pre
.........

The value of key target_names 

In [ ]:
print("Target names:{}".format(iris_dataset['target_names']))
Target names:['setosa','Versicolor','virginica']

The value of feature_name

In [ ]:
print('features names:\n{}'.format(iris_data['features_names']))
feature_names:
['Sepal lenght(cm)','Sepal Width(cm)','petal lenght(cm)','petal width(cm)']

numpy array

In [ ]:
print("type of data {}".format(type(iris_dataset['data'])))
type of data:<class 'numpy.ndarray'>

shape of data

In [ ]:
print("Shape of data: {}".format(iris_dataset['data'].shape))
shape of data:(150,4)

Data representation

In [ ]:
print("First Five colums of data: \n{}".format(iris_dataset['data'][:5]))
First five colums of data
[[5.1 3.5 1.4 0.2]
 [4.9 3.0 1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.0 3.6 1.4 0.2]]



Types of Target 

In [ ]:
print("tpye of target:{}".format(type(iris_dataset['target']))
Type of target: <class 'numpy.ndarray'>

Shape of Target

In [ ]:
print("Shape of target:{}".format(iris_dataset['target']))
shape of Target:(150, )

Result

In [ ]:
print("Target:\n{}".format(iris_dataset['target']))

Testing of Data

In [ ]:
From sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_spilt(
    iris_dataset['data'],iris_dataset['target'], random_state =0)

X_train = 75% and X_test = 25%

In [ ]:
print("X_train Shape:{}".format(X_train.shape))
print("Y_train Shape:{}".format(Y_train.shape))
print("X_test Shape:{}".format(X_test.shape))
print("Y_test Shape:{}".format(Y_test.shape))

X_train shape :(112,4)
Y_train shape :(112, )
X_test shape :(38,4)
Y_test shape :(38, )

Machine Learning Model(Bot)

In [ ]:
From sklearn.neighbors import KNeighborsClassifier
Knn = KKNeighborsClassifier(n_neighbors = 1)
Knn.Fit(X_train,Y_train)
KNeighborsClassifier(algorithms = 'auto',leaf_size = 30, metric = 
                     'minkowski',metric_params = none,
                     n_jobs = None, n_neighbors = 1, p  =2, Weight = 'uniform')

Making Predictions

In [ ]:
X_new = np.array([[5, 2.9, 1, 0.2]])
print("X_new.shape:{}".format(X_new.shape))
X_new.shape :(1,4)
prediction = Knn.predict(X_new)
print("prediction:{}".format(prediction))
print("predictiontarget_name :{}".format(iris_dataset['target_names']
                                         [prediction]))
prediction:[0]
prediction target name :['Setosa']

Evaluation

In [ ]:
Y_pred = Knn.predict(X_test)
print("TEst Set prediction :\n{}".format(Y_pred))
TEst set prediction:
[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0 2]

In [ ]:
print("Test set score: {}".format(np.mean(Y_pred == y_test)))
Test set score: 0.9736842105263158